"""add_actions

Revision ID: 390888ecf4d3
Revises: 95a57ddc7868
Create Date: 2024-02-25 01:48:49.976652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models.auth_orm_models import ActionsOrm


# revision identifiers, used by Alembic.
revision: str = "390888ecf4d3"
down_revision: Union[str, None] = "95a57ddc7868"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        table=ActionsOrm.__table__,
        rows=[
            {
                "id": 1,
                "action_name": "logout",
                "comment": "Разлогинивание пользователя",
            },
            {
                "id": 2,
                "action_name": "refresh_token",
                "comment": "Обновить пару токенов",
            },
            {
                "id": 3,
                "action_name": "history",
                "comment": "Получить историю авторизации",
            },
            {"id": 4, "action_name": "change_password", "comment": "Изменить пароль"},
            {"id": 5, "action_name": "create_role", "comment": "Создать роль"},
            {"id": 6, "action_name": "delete_role", "comment": "Удалить роль"},
            {"id": 7, "action_name": "change_role", "comment": "Изменить роль"},
            {"id": 8, "action_name": "get_roles", "comment": "Просмотр всех ролей"},
            {"id": 9, "action_name": "set_role", "comment": "Назначить роль"},
            {"id": 10, "action_name": "grab_role", "comment": "Отобрать роль"},
            {
                "id": 11,
                "action_name": "check_role",
                "comment": "Проверка роли у пользователя",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text("DELETE FROM actions r where r.id in (1, 2, 3, 4, 5, 6, 7, 8, 9, 10);")
    )
    # ### end Alembic commands ###
