"""delete_device_id

Revision ID: aa43e8f099bd
Revises: 5401416ce39f
Create Date: 2024-02-29 22:49:46.165850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa43e8f099bd'
down_revision: Union[str, None] = '5401416ce39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_history', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=256),
               comment='Устройства',
               existing_comment='ID устройства',
               existing_nullable=True)
    op.alter_column('user_data', 'register_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_comment='Дата регистрации пользователя',
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_data', 'register_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_comment='Дата регистрации пользователя',
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('auth_history', 'device_id',
               existing_type=sa.String(length=256),
               type_=sa.INTEGER(),
               comment='ID устройства',
               existing_comment='Устройства',
               existing_nullable=True)
    # ### end Alembic commands ###
